#!/bin/bash

#A simple script
#@Author: RB
#@version 0.1


BLUE='\033[1;36m'
RED='\033[1;31m'
GREEN='\033[1;32m'
NC='\033[0m'

set -e
set -o pipefail

echo -e "${GREEN}[*] creating a hotspot Kali-Hotspot ${NC}"
IFNAME="wlan1"
CON_NAME="Kiwa-Hotspot" 
PASSWD="Test@1234" 
nmcli c add type wifi ifname $IFNAME con-name $CON_NAME autoconnect yes ssid $CON_NAME 802-11-wireless.mode ap 802-11-wireless.band a wifi-sec.key-mgmt wpa-psk wifi-sec.psk "$PASSWD"
echo -e "${GREEN}[*] using nmcli to enable connection ${NC}"
nmcli con up $CON_NAME
#echo -e "${GREEN}[*] Disabling security settings ${NC}"
#nmcli con mod $CON_NAME wifi-sec.pmf disable
echo -e "${GREEN}[*] Checking connections ${NC}"
nmcli d s | grep ^$IFNAME
