#!/bin/bash

GREEN='\033[1;32m'
NC='\033[0m'


echo -e "${GREEN}[*] If a pdf is provided in \$1, it will automatically try to encrypt the report with the password. ${NC}"
echo -e "\n${GREEN}[*] Generating and displaying the password ${NC}"
tr -dc 'A-Za-z0-9!"#$%&'\''()*+,-./:;<=>?@[\]^_`{|}~' </dev/urandom | head -c 13 | tee -a passwd.txt

echo -e "\n${GREEN}[*] Saving the password to $(pwd)/passwd.txt ${NC}"


if [ ! -z "$1" ];
then
    NAME=`echo "$1" | cut -d'.' -f1`
    EXTENSION=`echo "$1" | cut -d'.' -f2`

    # if the file is provided:
    echo -e "\n${GREEN}[*] Using the following directory for input and output $(pwd)/ ${NC}"

    currentdir=$(pwd)
    PASSWD=$(cat passwd.txt)

    if [[ "$1" == *.pdf ]]; then
        qpdf --encrypt $PASSWD $PASSWD 256 -- "$(pwd)/$1" "$(pwd)/protected_$1"
        echo -e "\n${GREEN}[*] The report is now also encrypted with the set passwd. ${NC}"
    elif [[ "$1" == *.zip ]]; then
        zip -e $1 -p $passwd
        echo -e "\n${GREEN}[*] The zip is now also encrypted with the set passwd. ${NC}"
    else
        echo -e "\n${GREEN}[*] invalid file extension. ${NC}"
    fi
fi

: '
##this script will most likely start using the generation option in Keepass instead.

if [ -f ~/Projects/Passwords.kdbx ]; then
    echo -e "\n${GREEN}[*] File exists ${NC}"
    read -p "Enter the company you did the test for: " companyname
    read -p "enter the type of test you did: " typetest
    read -p "Enter the product/componentname you tested: " componentname
    echo $(cat passwd.txt) | keepassxc-cli add ~/Projects/Passwords.kdbx -u "$companyname-$typetest-$componentname" -g "Report Password" -p
else
   echo "File  does not exist. Not running keepassxc-cli"
fi
'