#!/bin/bash

#@Author: RB
#@Version: 0.1

BLUE='\033[1;36m'
RED='\033[1;31m'
GREEN='\033[1;32m'
NC='\033[0m'

TARGET_DIR="./400_Report/"

download_typst() {
    echo -e "${GREEN}[*] Checking GitHub SSH access...${NC}"

    # Test SSH connection to GitHub
    ssh -T git@github.com 2>&1 | grep -q "successfully authenticated"

    if [ $? -ne 0 ]; then
        echo -e "${RED}[*] ❌ GitHub SSH access failed. ${NC}"
        echo -e "${RED}[*] Make sure your SSH key is added to GitHub and ssh-agent is running. ${NC}"
        exit 1
    else
        echo -e "${GREEN}[*] ✅ GitHub SSH access succesful.${NC}"
        git clone --mirror "git@github.com:KiwaProductCybersecurity/kiwatypst.git" "./400_Report/typst/"
        git clone "./400_Report/typst.git/" "./400_Report/typst/"    
    fi  
}

# Get current directory name
CURRENT_DIR="$(basename "$PWD")"

# Case 1: already in the target directory
if [[ "$CURRENT_DIR" == "$TARGET_DIR" ]]; then
    echo -e "${GREEN}[*] Already in '$TARGET_DIR' ${NC}"
    download_typst
# Case 2: target directory exists as a subfolder
elif [[ -d "$TARGET_DIR" ]]; then
    cd $TARGET_DIR
    download_typst
else
    echo -e "${RED}[*] ❌ '$TARGET_DIR' not found (not current dir, not a subfolder)"
    exit 2        
fi