#!/bin/bash

#Thanks to FlorianHegele: https://github.com/FlorianHegele/AutoUpdateDiscord/tree/main
#I only added fancy colors. 
#@Author: RB
#@Version: 0.1


BLUE='\033[1;36m'
RED='\033[1;31m'
GREEN='\033[1;32m'
NC='\033[0m'

# Function to obtain the currently installed version of Discord
get_installed_version() {
    local installed_version=$(dpkg-query -W -f='${Version}\n' discord 2>/dev/null)
    echo $installed_version
}

# Function to get the latest version of Discord from the API
get_latest_version() {
    local latest_version_url="https://discord.com/api/download/stable?platform=linux&format=deb"
    local download_url=$(curl -sI $latest_version_url | grep -i '^location' | awk '{print $2}' | tr -d '\r\n')
    echo $download_url
}

# Function to download and install the latest version of Discord
update_discord() {
    local download_url=$1
    local temp_dir=$(mktemp -d)
    local filename=$(basename $download_url)
    local download_path="$temp_dir/$filename"

    echo "$temp_dir tmp dir"
    echo "$download_path path"
    
    echo -e "${GREEN}[*] Download the latest version of Discord...${NC}"
    curl -# -L -o $download_path $download_url

    if [ -f $download_path ]; then
        echo -e "${GREEN}[*] Installing the new version of Discord...${NC}"
        sudo dpkg -i $download_path
        rm $download_path

        echo -e "${GREEN}[*] Discord has been successfully updated!${NC}"
    else
        echo -e "${GREEN}[*] Failed to download the latest version of Discord.${NC}"
    fi

    rm -rf $temp_dir
}

installed_version=$(get_installed_version)
latest_version_url=$(get_latest_version)

if [ -z "$installed_version" ]; then
    echo -e "${GREEN}[*] Discord is not installed on this system.${NC}"
    echo -e "${GREEN}[*] Download and install the latest version of Discord...${NC}"
    update_discord $latest_version_url
    exit
fi

if [ -n "$latest_version_url" ]; then
    latest_version=$(echo "$latest_version_url" | cut -d '/' -f 6)
    if [[ "$installed_version" != "$latest_version" ]]; then
        echo -e "${GREEN}[*] A new version of Discord is available. Update in progress...${NC}"
        update_discord $latest_version_url
    else
        echo -e "${GREEN}[*] The currently installed version of Discord is already up to date.${NC}"
    fi
else
    echo -e "${GREEN}[*] Unable to get the latest version of Discord from the API.${NC}"
fi