#!/bin/bash

#A simple script
#@Author: RB
#@version 0.1


BLUE='\033[1;36m'
RED='\033[1;31m'
GREEN='\033[1;32m'
NC='\033[0m'

set -e
set -o pipefail

currentfolder=$(basename "$PWD")

echo -e "${GREEN}[*] Zipping $currentfolder.${NC}"
echo -e "${GREEN}[*] Prompting for a password to encrypt the zip (and make it not directly detectable by Defender) ${NC}"
zip -e -r $currentfolder.zip .